In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# If you wish to grab a single element from an array you just call the array and it's index location

arr[4]

4

In [4]:
arr[8]

8

In [5]:
# To grab several elements in a row you can use the index as well

arr[1:4]

array([1, 2, 3])

In [6]:
arr[5:9]

array([5, 6, 7, 8])

In [7]:
## To start the list from the beginning you can omit the first element

arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
## To start in the middle of the array and go to the end, omit the last element

arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [9]:
## Using these indexes you can reassign selected elements without altering the entire array

arr[:5] = 123

arr

array([123, 123, 123, 123, 123,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0, 11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Indexing can also be used to assign a partial array to a new variable

arr2 = arr[:5]

arr2

array([0, 1, 2, 3, 4])

In [12]:
## The colon by itself allows you to select the entire array

arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
## Altering arr2 will alter arr since it is a subset of the same data

## If you want to alter the data in the subset without altering the original use the .copy() function

arr3 = arr2.copy()

arr3

array([0, 1, 2, 3, 4])

In [15]:
arr2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
# Using an index in a multi dimensional array will retrieve the entire array 

arr2d[0]

array([ 5, 10, 15])

In [17]:
## To further access a single element within that array, you can add a dimension to your index

arr2d[0, 0]

5

In [20]:
# Mathmatical operators can be used to filter arrays with bool values indicating if the expression is true
arr2d > 30

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [22]:
## Using brackets you can filter to only recive values where the expression is true
arr2d[arr2d > 10]

array([15, 20, 25, 30, 35, 40, 45])

## Coding Exercise 2



In [23]:
# TASK: Use numpy to check how many rolls were greater than 2. 
# For example if dice_rolls=[1,2,3] then the answer is 1.
# NOTE: Many different ways to do this! Your final answer should be an integer.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/ea3121efac5dd3338c280ff10068f9c8

import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

# total_rolls_over_two = # This should be a single integer

In [24]:
larger_than_2 = dice_rolls[dice_rolls > 2]

larger_than_2

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [26]:
total_rolls_over_two = len(larger_than_2)

total_rolls_over_two

19