In [1]:
# Numpy must first be imported into your python environment

import numpy as np

In [2]:
# the np.array() function is used to create a new array

my_list = [1, 2, 3, 4, 5, 6]

my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5, 6])

In [3]:
type(my_array)

numpy.ndarray

In [4]:
# Numpy arrays can take in multi dimenstional lists and convert them into a matrix

my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
my_array2 = np.array(my_matrix)

my_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# The np.arange() function allows you to use the range() function to create an array

my_array3 = np.arange(0, 10)

my_array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
## The format for this function is np.arange(starting_point, end_point, n_steps)

my_array4 = np.arange(0, 101, 2)

my_array4

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [9]:
# The np.zeros() function allows you to create an array of all 0's as floats

my_array5 = np.zeros(5)

my_array5

array([0., 0., 0., 0., 0.])

In [10]:
## The zeros() function can be used to create multi dimensional arrays as well

my_array6 = np.zeros((5, 5))

my_array6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
## The np.ones() function is similar to zeros, as it creates an array of 1's

my_array7 = np.ones((3,6))

my_array7

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
# Another method of making an array is np.linspace()
# Which will provide evenly spaced numbers in a specifed range

## The format for this function is np.linspace(start, end, n_numbers)
my_array8 = np.linspace(1, 100, 11)

my_array8

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [15]:
# The np.random.rand(n_rows, n_cols) function will create an array of random numbers between 0 and 1

## This function will return random numbers with uniform distribution

my_array9 = np.random.rand(2, 4)

my_array9

array([[0.97690519, 0.73130703, 0.53982384, 0.8984511 ],
       [0.4494599 , 0.19296322, 0.45572926, 0.85925322]])

In [16]:
## To get random numbers with a normal distrubtion we can us np.random.randn()

my_array10 = np.random.randn(3, 3)

my_array10

array([[ 0.45258942, -2.18444813,  0.93463221],
       [ 1.54878852,  0.35172912,  0.59579468],
       [ 1.25042724, -0.83050246,  0.5038254 ]])

In [17]:
## To get a random array of whole integers, you may use np.random.randint()

### The syntax being np.random.randint(lowest_int, highest_int, n_values)

my_array11 = np.random.randint(0, 101, 34)

my_array11

array([ 6, 89, 16, 31, 81, 36, 52, 50, 28,  2, 70, 19, 40, 63, 81, 25, 75,
       26,  3, 98, 99, 91, 20, 33, 25, 80, 76, 81, 28, 91, 68, 60, 74, 78])