In [1]:
# Numpy must first be imported into your python environment

import numpy as np

In [2]:
# the np.array() function is used to create a new array

my_list = [1, 2, 3, 4, 5, 6]

my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5, 6])

In [3]:
type(my_array)

numpy.ndarray

In [4]:
# Numpy arrays can take in multi dimenstional lists and convert them into a matrix

my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
my_array2 = np.array(my_matrix)

my_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# The np.arange() function allows you to use the range() function to create an array

my_array3 = np.arange(0, 10)

my_array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
## The format for this function is np.arange(starting_point, end_point, n_steps)

my_array4 = np.arange(0, 101, 2)

my_array4

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [9]:
# The np.zeros() function allows you to create an array of all 0's as floats

my_array5 = np.zeros(5)

my_array5

array([0., 0., 0., 0., 0.])

In [10]:
## The zeros() function can be used to create multi dimensional arrays as well

my_array6 = np.zeros((5, 5))

my_array6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
## The np.ones() function is similar to zeros, as it creates an array of 1's

my_array7 = np.ones((3,6))

my_array7

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
# Another method of making an array is np.linspace()
# Which will provide evenly spaced numbers in a specifed range

## The format for this function is np.linspace(start, end, n_numbers)
my_array8 = np.linspace(1, 100, 11)

my_array8

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [15]:
# The np.random.rand(n_rows, n_cols) function will create an array of random numbers between 0 and 1

## This function will return random numbers with uniform distribution

my_array9 = np.random.rand(2, 4)

my_array9

array([[0.97690519, 0.73130703, 0.53982384, 0.8984511 ],
       [0.4494599 , 0.19296322, 0.45572926, 0.85925322]])

In [16]:
## To get random numbers with a normal distrubtion we can us np.random.randn()

my_array10 = np.random.randn(3, 3)

my_array10

array([[ 0.45258942, -2.18444813,  0.93463221],
       [ 1.54878852,  0.35172912,  0.59579468],
       [ 1.25042724, -0.83050246,  0.5038254 ]])

In [17]:
## To get a random array of whole integers, you may use np.random.randint()

### The syntax being np.random.randint(lowest_int, highest_int, n_values)

my_array11 = np.random.randint(0, 101, 34)

my_array11

array([ 6, 89, 16, 31, 81, 36, 52, 50, 28,  2, 70, 19, 40, 63, 81, 25, 75,
       26,  3, 98, 99, 91, 20, 33, 25, 80, 76, 81, 28, 91, 68, 60, 74, 78])

In [18]:
# Random seeds allow you to ensure you get the same random results as others using the same seed

## This is necessary for your work to be reproducable by others

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [19]:
## So long as you are using the same random seed, you will always return the same random numbers

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [21]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [22]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [23]:
## With no seed you will get different random numbers every time

### This is not good for reproducing your work

np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [24]:
np.random.rand(4)

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

In [25]:
np.random.rand(4)

array([0.1818924 , 0.78560176, 0.96548322, 0.23235366])

In [26]:
# The reshape() function allows you to change the shape of arrays from 1 to multi dimensional

my_array11

array([ 6, 89, 16, 31, 81, 36, 52, 50, 28,  2, 70, 19, 40, 63, 81, 25, 75,
       26,  3, 98, 99, 91, 20, 33, 25, 80, 76, 81, 28, 91, 68, 60, 74, 78])

In [27]:
## Reshape size MUST equal size of entire array

my_array11.reshape(2, 17)

array([[ 6, 89, 16, 31, 81, 36, 52, 50, 28,  2, 70, 19, 40, 63, 81, 25,
        75],
       [26,  3, 98, 99, 91, 20, 33, 25, 80, 76, 81, 28, 91, 68, 60, 74,
        78]])

In [29]:
# The max() and min() functions allow you to find the highest and lowest value in your array

my_array11.max()

99

In [30]:
my_array11.min()

2

In [31]:
## The argmax() and argmin() functions can be used to find the location of the highest and lowest values

my_array11.argmax()

20

In [32]:
my_array11.argmin()

9

In [34]:
# The .dtype function will tell you the data type of your array

my_array11.dtype

dtype('int64')

In [35]:
# Call .shape to see the size of your array

my_array11.shape

(34,)

In [36]:
my_array2.shape

(3, 3)

- Coding Exercise

In [37]:
# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.

# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.

# Link to Solution: https://gist.github.com/Pierian-Data/ea9c4d2fc6c98ac74af18134cd924867
import numpy as np
myarray = np.linspace(0, 10, 101)

In [38]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])