In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Using matematical operators will affect every item in the array

arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Arrays can also be applied to each other, but they MUST be the same shape

arr2 = arr * arr

arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
# Various functions can be used to tell you about your array

arr.max()

9

In [6]:
arr.sum()

45

In [7]:
arr.var()

8.25

In [8]:
arr2d = np.arange(0, 25).reshape(5, 5)

arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
# When working with multi dimensional arrays you can specify what further with arguments on your functions

arr2d.max(axis = 0)

array([20, 21, 22, 23, 24])

In [10]:
arr2d.max(axis = 1)

array([ 4,  9, 14, 19, 24])

# Coding Exercise 3



In [11]:
# TASK: Use numpy to check the total remaining in the account after the series of transactions.
# NOTE: Many different ways to do this! 
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/225a449484e12e0535fbbac2231b426b

import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

# account_total =  

In [13]:
account_total = account_transactions.sum()

account_total

2720